# define some parameters which will be loaded into the main script `LookupBot.py`
client_id: ""
client_secret: ""

# if any of these words get detected in a submission or comment to any of the subreddits listed below, the submission/comment will be safed to the
# output file

keywords:
  - "internship"
  - "junior"
  - "entry"
  - "intern"

subreddits:
  - "bioinformatics"
  - "genomics"
  - "datascience"

output_file: "extracted_results.yaml"